FROM nginx:stable-alpine

COPY frontend/index.html /usr/share/nginx/html/index.html
COPY frontend/notes.css /usr/share/nginx/html/notes.css
COPY frontend/notes.js /usr/share/nginx/html/notes.js

RUN sed -i 's|^const API_URL = "http://127.0.0.1:8001";$|const API_URL = "/apps/notes/api";|' /usr/share/nginx/html/notes.js

COPY nginx.notes.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
